version: '2'
services:
  ##### the develop image you've build
  ### don't forget to open ports for your app
  dev-image:
    image: esp32/develop_build
    user: root
    privileged: true
    container_name: esp32_make_dev_app
    stdin_open: true
    tty: true
# mapping your project folder (.) to /home/develop/project    
    volumes:
      - "../Code/./:/home/develop/project"
    working_dir: /home/develop/project/